registers/ir.v
testbenches/ir_tb.v
gates/and.v
gates/nand.v
gates/or.v
gates/not.v
gates/nor.v
gates/xor.v
composites/bAdd.v
composites/dff.v
composites/dLatch.v
composites/mux2.v
composites/mux8.v
composites/dff_sync_set_reset.v
alu/add8.v
alu/alu.v
alu/and8.v
alu/not8.v
alu/or8.v
alu/inc8.v
alu/sub8.v
alu/xor8.v
alu/zero8.v
registers/reg8.v
registers/pc.v
testbenches/add8_tb.v
testbenches/and_tb.v
testbenches/and8_tb.v
testbenches/bAdd_tb.v
testbenches/dff_tb.v
testbenches/dLatch_tb.v
testbenches/mux2_tb.v
testbenches/nand_tb.v
testbenches/not_tb.v
testbenches/or_tb.v
testbenches/xor_tb.v
testbenches/sub8_tb.v
testbenches/inc8_tb.v
testbenches/zero8_tb.v
testbenches/mux8_tb.v
testbenches/alu_tb.v
testbenches/dff_sync_set_reset_tb.v
testbenches/reg8_tb.v
testbenches/pc_tb.v
