cpu.v
gates/and.v
gates/nand.v
gates/or.v
gates/not.v
gates/nor.v
gates/xor.v
composites/bAdd.v
composites/dff.v
composites/dLatch.v
composites/mux2.v
composites/mux8.v
composites/dff_sync_set_reset.v
composites/decoder2to4.v
composites/decoder4to16.v
composites/tri_buf.v
alu/add8.v
alu/alu.v
alu/and8.v
alu/not8.v
alu/or8.v
alu/inc8.v
alu/sub8.v
alu/xor8.v
alu/zero8.v
registers/reg8.v
registers/pc.v
registers/ir.v
registers/gpr.v
registers/load_reg8.v
registers/flags_reg.v
memory/ram.v
memory/rom.v
testbenches/alu/add8_tb.v
testbenches/gates/and_tb.v
testbenches/alu/and8_tb.v
testbenches/composites/bAdd_tb.v
testbenches/composites/dff_tb.v
testbenches/composites/dLatch_tb.v
testbenches/composites/mux2_tb.v
testbenches/gates/nand_tb.v
testbenches/gates/not_tb.v
testbenches/gates/or_tb.v
testbenches/gates/xor_tb.v
testbenches/alu/sub8_tb.v
testbenches/alu/inc8_tb.v
testbenches/alu/zero8_tb.v
testbenches/composites/mux8_tb.v
testbenches/alu/alu_tb.v
testbenches/composites/dff_sync_set_reset_tb.v
testbenches/registers/reg8_tb.v
testbenches/registers/pc_tb.v
testbenches/registers/gpr_tb.v
testbenches/registers/ir_tb.v
testbenches/memory/ram_tb.v
testbenches/memory/rom_tb.v
testbenches/control/control_unit_tb.v
testbenches/cpu_tb.v
